'use client';

import { useState, useEffect } from 'react';
import { Plus, Trash2, Save, AlertCircle, Check, Sparkles, BookOpen } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { Resolution, PointODJ, ModeleResolution, TypeVote, TYPE_VOTE_LABELS, OPTIONS_VOTE_STANDARD } from '@/types';
import { getSession, saveSession, getAllSessions, getAllModeles } from '@/lib/db';
import { generateId, generateResolution, searchModeles } from '@/lib/parser';

export default function ResolutionsPage() {
  const router = useRouter();
  const [sessions, setSessions] = useState<{ id: string; titre: string }[]>([]);
  const [selectedSessionId, setSelectedSessionId] = useState<string>('');
  const [resolutions, setResolutions] = useState<Resolution[]>([]);
  const [modeles, setModeles] = useState<ModeleResolution[]>([]);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  const [autoGenerated, setAutoGenerated] = useState(false);

  useEffect(() => {
    loadData();
  }, []);

  async function loadData() {
    const allSessions = await getAllSessions();
    setSessions(allSessions.map(s => ({ id: s.id, titre: s.titre || 'Sans titre' })));
    
    const allModeles = await getAllModeles();
    setModeles(allModeles);
    
    if (allSessions.length > 0) {
      if (!selectedSessionId) {
        setSelectedSessionId(allSessions[0].id);
      }
      loadResolutions(allSessions[0].id);
    }
  }

  async function loadResolutions(sessionId: string) {
    const session = await getSession(sessionId);
    if (session) {
      setResolutions(session.resolutions || []);
    }
  }

  async function handleSessionChange(id: string) {
    setSelectedSessionId(id);
    setAutoGenerated(false);
    await loadResolutions(id);
  }

  async function generateAllResolutions() {
    if (!selectedSessionId) return;
    
    const session = await getSession(selectedSessionId);
    if (!session?.ordreDuJour) return;

    const points = session.ordreDuJour.points;
    const newResolutions: Resolution[] = [];

    for (const point of points) {
      const matchingModeles = searchModeles(point.motsCles || [], modeles);
      const resolution = generateResolution(point, matchingModeles[0]);
      newResolutions.push(resolution);
    }

    setResolutions(newResolutions);
    setAutoGenerated(true);
    setMessage({ type: 'success', text: `${newResolutions.length} résolutions générées!` });
  }

  async function handleSave() {
    if (!selectedSessionId) return;
    setSaving(true);
    setMessage(null);

    try {
      const session = await getSession(selectedSessionId);
      if (session) {
        session.resolutions = resolutions;
        session.dateModification = new Date();
        await saveSession(session);
        setMessage({ type: 'success', text: 'Résolutions sauvegardées!' });
      }
    } catch (err) {
      setMessage({ type: 'error', text: 'Erreur lors de la sauvegarde' });
    } finally {
      setSaving(false);
    }
  }

  function addResolution(): void {
    const newResolution: Resolution = {
      id: generateId(),
      numero: resolutions.length > 0 
        ? (Math.max(...resolutions.map(r => parseFloat(r.numero) || 0)) + 1).toString()
        : '1',
      titre: 'Nouvelle résolution',
      contenu: '',
      typeVote: 'article_24',
      optionsVote: OPTIONS_VOTE_STANDARD,
      source: 'manuel',
      dateCreation: new Date(),
    };
    setResolutions([...resolutions, newResolution]);
  }

  function updateResolution(id: string, field: keyof Resolution, value: unknown) {
    setResolutions(resolutions.map(r => 
      r.id === id ? { ...r, [field]: value } : r
    ));
  }

  function deleteResolution(id: string) {
    setResolutions(resolutions.filter(r => r.id !== id));
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-primary font-heading">Résolutions</h1>
        <p className="text-muted mt-2">Gérez les résolutions et leurs modes de vote</p>
      </div>

      {sessions.length === 0 ? (
        <div className="card">
          <p className="text-muted mb-4">Aucune session trouvée.</p>
          <button onClick={() => router.push('/import')} className="btn-primary">
            Importer une convocation
          </button>
        </div>
      ) : (
        <>
          <div className="card">
            <label className="label">Session</label>
            <select 
              value={selectedSessionId}
              onChange={(e) => handleSessionChange(e.target.value)}
              className="input"
            >
              {sessions.map(s => (
                <option key={s.id} value={s.id}>{s.titre}</option>
              ))}
            </select>
          </div>

          <div className="flex gap-4">
            <button 
              onClick={generateAllResolutions} 
              className="btn-primary flex items-center gap-2"
            >
              <Sparkles size={20} />
              Générer automatiquement
            </button>
            <button 
              onClick={addResolution}
              className="btn-secondary flex items-center gap-2"
            >
              <Plus size={20} />
              Ajouter une résolution
            </button>
            <button 
              onClick={handleSave} 
              disabled={saving}
              className="btn-accent flex items-center gap-2"
            >
              <Save size={20} />
              {saving ? 'Sauvegarde...' : 'Sauvegarder'}
            </button>
          </div>

          {resolutions.length === 0 ? (
            <div className="card text-center py-12">
              <BookOpen className="mx-auto text-gray-300 mb-4" size={48} />
              <p className="text-muted mb-4">Aucune résolution. Générez-les automatiquement ou ajoutez-les manuellement.</p>
            </div>
          ) : (
            <div className="space-y-4">
              {resolutions.map((resolution, index) => (
                <div key={resolution.id} className="card">
                  <div className="flex items-start gap-4 mb-4">
                    <div className="w-20 flex-shrink-0">
                      <label className="label">N°</label>
                      <input
                        type="text"
                        value={resolution.numero}
                        onChange={(e) => updateResolution(resolution.id, 'numero', e.target.value)}
                        className="input text-center font-bold"
                      />
                    </div>
                    <div className="flex-1">
                      <label className="label">Titre</label>
                      <input
                        type="text"
                        value={resolution.titre}
                        onChange={(e) => updateResolution(resolution.id, 'titre', e.target.value)}
                        className="input"
                      />
                    </div>
                    <button
                      onClick={() => deleteResolution(resolution.id)}
                      className="mt-6 p-2 text-red-600 hover:bg-red-50 rounded"
                    >
                      <Trash2 size={20} />
                    </button>
                  </div>

                  <div className="mb-4">
                    <label className="label">Contenu</label>
                    <textarea
                      value={resolution.contenu}
                      onChange={(e) => updateResolution(resolution.id, 'contenu', e.target.value)}
                      className="input h-24"
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="label">Type de vote</label>
                      <select
                        value={resolution.typeVote}
                        onChange={(e) => updateResolution(resolution.id, 'typeVote', e.target.value as TypeVote)}
                        className="input"
                      >
                        {Object.entries(TYPE_VOTE_LABELS).map(([value, label]) => (
                          <option key={value} value={value}>{label}</option>
                        ))}
                      </select>
                    </div>
                    <div>
                      <label className="label">Options de vote</label>
                      <input
                        type="text"
                        value={resolution.optionsVote.join(', ')}
                        onChange={(e) => updateResolution(resolution.id, 'optionsVote', e.target.value.split(',').map(s => s.trim()))}
                        className="input"
                      />
                    </div>
                  </div>

                  <div className="mt-2 text-xs text-muted">
                    Source: {resolution.source} {resolution.source === 'bibliotheque' && '• Modèle utilisé'}
                  </div>
                </div>
              ))}
            </div>
          )}

          {message && (
            <div className={`flex items-center gap-2 p-4 rounded-lg ${
              message.type === 'success' ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700'
            }`}>
              {message.type === 'success' ? <Check size={20} /> : <AlertCircle size={20} />}
              {message.text}
            </div>
          )}
        </>
      )}
    </div>
  );
}